apiVersion: v1
kind: Service
metadata:
  name: {{ include "procare.fullname" . }}-kafka
  labels:
    {{- include "procare.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: tcp-kafka
    port: 9092
    protocol: TCP
    targetPort: tcp-kafka
  selector:
    app: kafka