apiVersion: v1
kind: Service
metadata:
  name: {{ include "procare.fullname" . }}-kafka
  labels:
    {{- include "procare.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9092
      protocol: TCP
      name: http
  selector:
    {{- include "procare.selectorLabels" . | nindent 4 }}
